#!/usr/bin/env python3
"""Generate MCP discovery schemas and reference docs from mcp/server.py."""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "mcp"))

import server  # noqa: E402


def json_block(value: dict) -> str:
    return "```json\n" + json.dumps(value, indent=2, ensure_ascii=False) + "\n```"


async def generate() -> None:
    tools = await server.mcp.list_tools()
    resources = await server.mcp.list_resources()
    templates = await server.mcp.list_resource_templates()

    discovery_path = ROOT / "mcp.json"
    discovery = json.loads(discovery_path.read_text(encoding="utf-8"))
    discovery["tools"] = [
        {
            "name": tool.name,
            "description": tool.description,
            "inputSchema": tool.parameters,
        }
        for tool in tools
    ]
    discovery_path.write_text(
        json.dumps(discovery, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    lines = [
        "# MCP reference",
        "",
        "<!-- Generated by scripts/gen_mcp_reference.py from mcp/server.py. -->",
        "",
        "DataPulse MY exposes a read-only Streamable HTTP endpoint at",
        "`https://mcp.data-pulse.my/mcp`. It requires no authentication.",
        "",
        "Clients must send `Accept: application/json, text/event-stream` and use the",
        "session ID returned by the initialize response for subsequent calls.",
        "",
        "## Tools",
        "",
    ]
    for tool in tools:
        lines.extend(
            [
                f"### `{tool.name}`",
                "",
                tool.description or "",
                "",
                "Input schema:",
                "",
                json_block(tool.parameters),
                "",
            ]
        )

    lines.extend(["## Resources", ""])
    for resource in resources:
        lines.extend(
            [
                f"- `{resource.uri}` — {resource.description}",
                "",
            ]
        )
    for template in templates:
        lines.extend(
            [
                f"- `{template.uri_template}` — {template.description}",
                "",
            ]
        )

    lines.extend(
        [
            "## Regenerate",
            "",
            "Install `mcp/requirements.txt`, then run:",
            "",
            "```sh",
            "python3 scripts/gen_mcp_reference.py",
            "```",
            "",
            "The command updates this file and the tool schemas in `mcp.json`.",
            "",
        ]
    )
    (ROOT / "docs/mcp-reference.md").write_text("\n".join(lines), encoding="utf-8")
    print(
        f"Generated {len(tools)} tools, {len(resources)} resources, "
        f"and {len(templates)} resource templates"
    )


if __name__ == "__main__":
    asyncio.run(generate())
