#!/usr/bin/env python3
"""Generate MCP discovery schemas and reference docs from mcp/server.py."""

from __future__ import annotations

import asyncio
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "mcp"))

import server  # noqa: E402


LIVE_VERIFICATION = """## Live verification

Run before merging any change that touches the manifest, probe policy, or MCP
source. The live `datapulse://index` resource is the catalogue returned by the
MCP server, so its array length must equal the current manifest length.

```bash
verify_dir=$(mktemp -d /tmp/datapulse-mcp-live.XXXXXX)
endpoint=https://mcp.data-pulse.my/mcp

curl -sS -D "$verify_dir/headers" -o "$verify_dir/initialize" \\
  "$endpoint" \\
  -H 'Accept: application/json, text/event-stream' \\
  -H 'Content-Type: application/json' \\
  -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"live-count-gate","version":"1"}}}'

session_id=$(awk 'tolower($1)=="mcp-session-id:" {gsub("\\\\r", "", $2); print $2}' \\
  "$verify_dir/headers")

curl -sS "$endpoint" \\
  -H 'Accept: application/json, text/event-stream' \\
  -H 'Content-Type: application/json' \\
  -H "Mcp-Session-Id: $session_id" \\
  -d '{"jsonrpc":"2.0","method":"notifications/initialized"}' >/dev/null

live_count=$(curl -sS "$endpoint" \\
  -H 'Accept: application/json, text/event-stream' \\
  -H 'Content-Type: application/json' \\
  -H "Mcp-Session-Id: $session_id" \\
  -d '{"jsonrpc":"2.0","id":2,"method":"resources/read","params":{"uri":"datapulse://index"}}' \\
  | sed -n 's/^data: //p' \\
  | jq -r '.result.contents[0].text | fromjson | length')
head_count=$(jq '.datasets | length' datapulse.json)

printf 'live=%s head=%s\\n' "$live_count" "$head_count"
test "$live_count" -eq "$head_count"
```

The expected count at this revision is `DATASET_COUNT`. If the assertion fails, do not
merge: the MCP server is stale and the manifest-count claim is false.
""".replace("DATASET_COUNT", str(server.DATASET_COUNT))


def json_block(value: dict) -> str:
    return "```json\n" + json.dumps(value, indent=2, ensure_ascii=False) + "\n```"


async def generate() -> None:
    tools = await server.mcp.list_tools()
    resources = await server.mcp.list_resources()
    templates = await server.mcp.list_resource_templates()

    discovery_path = ROOT / "mcp.json"
    discovery = json.loads(discovery_path.read_text(encoding="utf-8"))
    discovery["server"]["source_commit_sha"] = server.SOURCE_COMMIT_SHA
    discovery["server"]["source_commit_date"] = server.SOURCE_COMMIT_DATE
    discovery["server"]["description"] = re.sub(
        r"\(\d+ datasets,",
        f"({server.DATASET_COUNT} datasets,",
        discovery["server"]["description"],
    )
    for resource in discovery.get("resources", []):
        if resource.get("uri") == "datapulse://index":
            resource["description"] = re.sub(
                r"all \d+ datasets",
                f"all {server.DATASET_COUNT} datasets",
                resource["description"],
            )
    discovery["tools"] = [
        {
            "name": tool.name,
            "description": tool.description,
            "inputSchema": tool.parameters,
        }
        for tool in tools
    ]
    discovery["resources"] = [
        {
            "uri": str(resource.uri),
            "name": getattr(resource, "name", str(resource.uri)),
            "description": resource.description,
            "mimeType": getattr(resource, "mime_type", "application/json"),
        }
        for resource in resources
    ] + [
        {
            "uri": template.uri_template,
            "name": getattr(template, "name", template.uri_template),
            "description": template.description,
            "mimeType": getattr(template, "mime_type", "application/json"),
        }
        for template in templates
    ]
    discovery_path.write_text(
        json.dumps(discovery, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    lines = [
        "# MCP reference",
        "",
        "<!-- Generated by scripts/gen_mcp_reference.py from mcp/server.py. -->",
        "",
        "DataPulse MY exposes a read-only Streamable HTTP endpoint at",
        "`https://mcp.data-pulse.my/mcp`. It requires no authentication.",
        "",
        "Clients must send `Accept: application/json, text/event-stream` and use the",
        "session ID returned by the initialize response for subsequent calls.",
        "",
        "## Tools",
        "",
    ]
    for tool in tools:
        lines.extend(
            [
                f"### `{tool.name}`",
                "",
                tool.description or "",
                "",
                "Input schema:",
                "",
                json_block(tool.parameters),
                "",
            ]
        )

    lines.extend(["## Resources", ""])
    for resource in resources:
        lines.extend(
            [
                f"- `{resource.uri}` — {resource.description}",
                "",
            ]
        )
    for template in templates:
        lines.extend(
            [
                f"- `{template.uri_template}` — {template.description}",
                "",
            ]
        )

    lines.extend(LIVE_VERIFICATION.splitlines() + [""])
    lines.extend(
        [
            "## Regenerate",
            "",
            "Install `mcp/requirements.txt`, then run:",
            "",
            "```sh",
            "python3 scripts/gen_mcp_reference.py",
            "```",
            "",
            "The command updates this file and the tool schemas in `mcp.json`.",
            "",
        ]
    )
    (ROOT / "docs/mcp-reference.md").write_text("\n".join(lines), encoding="utf-8")
    print(
        f"Generated {len(tools)} tools, {len(resources)} resources, "
        f"and {len(templates)} resource templates"
    )


if __name__ == "__main__":
    asyncio.run(generate())
