#!/usr/bin/env bash
#
# Refresh the legacy attestation chain head ahead of Sigstore signing.
#
# gen_sigstore_bundle.py refuses to sign unless .attestations/chain_head.json
# reports a dataset_count matching the current health snapshot. That head is
# only regenerated by the release-build profile, which runs after sign_health
# in the deploy workflow, so the signing step otherwise sees a stale head.
# This script closes the gap: it regenerates the attestations via
# gen_attestations.py (the only legitimate chain-head writer) and mirrors the
# fresh head into .attestations/chain_head.json. Nothing else is regenerated;
# the release-build profile still owns the remaining artifacts.
#
set -Eeuo pipefail

if (( $# > 1 )); then
  printf 'refresh_chain_head.sh: expected at most one argument: the private-key JSON path\n' >&2
  exit 2
fi

private_key="${1:-${DATAPULSE_ATTESTATION_PRIVATE_KEY_FILE:-}}"
if [[ -z "$private_key" ]]; then
  printf 'refresh_chain_head.sh: DATAPULSE_ATTESTATION_PRIVATE_KEY_FILE is not set and no private-key path argument was given; refusing to refresh the chain head without a signing key\n' >&2
  exit 2
fi

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

python3 scripts/gen_attestations.py --root . --private-key "$private_key"

# gen_attestations.generate() copies the fresh head into attestations/latest/
# but never into the top-level legacy envelope that
# gen_sigstore_bundle.py --legacy-chain-head consumes, so add that mirror.
cp attestations/latest/chain_head.json .attestations/chain_head.json

health_count="$(jq -er '.datasets | length' health/latest.json)"
head_count="$(jq -er '.payload.dataset_count' .attestations/chain_head.json)"
if [[ "$health_count" != "$head_count" ]]; then
  printf 'refresh_chain_head.sh: refreshed chain head dataset_count (%s) does not match canonical health (%s)\n' "$head_count" "$health_count" >&2
  exit 1
fi
